//AUTH_CONTEXT
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_USERINFO = "SET_USERINFO";

//ALERT_CONTEXT
export const ALERT_SHOW = "ALERT_SHOW";
export const ALERT_HIDE = "ALERT_HIDE";

//QUIZ_CONTEXT
export const QUIZ_START = "QUIZ_START";
export const QUIZ_RESTART = "QUIZ_RESTART";
export const QUIZ_SUCCESS = "QUIZ_SUCCESS";
export const QUIZ_CLEAR = "QUIZ_CLEAR";


//PARAMS_HISTORY
export const SET_PARAMS_HISTORY = "SET_PARAMS_HISTORY";
export const CHANGE_PARAMS_HISTORY_PAGE = "CHANGE_PARAMS_HISTORY";
export const CLEAR_PARAMS_HISTORY = "CLEAR_PARAMS_HISTORY";
